#!/usr/bin/env bash
#
# Fresh-VPS bootstrap for TimorMart — Ubuntu 22.04/24.04 LTS.
# (Overwhelmingly the default OS on new VPS instances; if your box runs
# something else — Debian, Rocky/CentOS — the package manager commands in
# section 1 are the only part that needs adjusting.)
#
# This is the committed TEMPLATE — same relationship as .env.example has
# to .env. It has no real credentials in it and is safe to commit/push.
# Copy it to setup_vps.local.sh (already .gitignore'd), fill in the
# SUPERUSER_* values and anything else you want to change, and run that
# copy instead — never put real secrets in this file.
#
# What this does:
#   - Installs Python, PostgreSQL, Nginx, Certbot, and build dependencies.
#   - Creates a dedicated, unprivileged system user to run the app.
#   - Creates a brand-new, EMPTY Postgres database — nothing is imported
#     or migrated from any existing database. `manage.py migrate` builds
#     the schema fresh; the only row that ends up in it is the superuser
#     account created at the bottom.
#   - Clones the repo, sets up a virtualenv, installs dependencies.
#   - Writes a .env with the values this script can actually generate
#     (SECRET_KEY, DATABASE_URL, the superuser credentials) — every
#     third-party integration (Stripe, Cloudinary, Resend, Firebase) is
#     left blank with a comment, since those are your own external
#     accounts, not something a server-provisioning script can invent.
#     The app runs fine with all of them blank (each one degrades to a
#     documented no-op — see .env.example) until you fill them in.
#   - Runs migrate + collectstatic, creates the superuser, and starts the
#     app under systemd + Nginx.
#
# Run as root (or with sudo) on the target server:
#   sudo bash setup_vps.local.sh
#
# Whichever copy of this script you actually run will contain a real
# password once SUPERUSER_PASSWORD is filled in — treat that copy like any
# other secret, and change the superuser password on first login regardless.

set -euo pipefail

# ── 1. Fill these in before running ──────────────────────────────────────

# The domain pointing at this server (e.g. "timormart.com"). Leave blank to
# skip Nginx/HTTPS setup for now and just serve on the bare IP over HTTP —
# you can re-run section 9 later once DNS is pointed here.
DOMAIN=""

REPO_URL="https://github.com/januariocosta84/onlineretail-live.git"
APP_USER="timormart"
APP_DIR="/srv/timormart"
DB_NAME="timormart"
DB_USER="timormart"
DB_PASSWORD="$(openssl rand -base64 24 | tr -d '/+=')"   # generated fresh, saved into .env below

SUPERUSER_USERNAME="CHANGE_ME"
SUPERUSER_PASSWORD="CHANGE_ME"
SUPERUSER_EMAIL="CHANGE_ME"

if [ "${SUPERUSER_USERNAME}" = "CHANGE_ME" ] || [ "${SUPERUSER_PASSWORD}" = "CHANGE_ME" ] || [ "${SUPERUSER_EMAIL}" = "CHANGE_ME" ]; then
  echo "Fill in SUPERUSER_USERNAME/PASSWORD/EMAIL (section 1) before running this — refusing to create an account with a literal 'CHANGE_ME' password." >&2
  exit 1
fi

# ── 2. System packages ────────────────────────────────────────────────────

apt-get update
apt-get install -y \
  python3 python3-venv python3-pip python3-dev \
  postgresql postgresql-contrib libpq-dev \
  nginx certbot python3-certbot-nginx \
  git build-essential curl ufw

# ── 3. PostgreSQL — fresh, empty database + role ─────────────────────────

sudo -u postgres psql -v ON_ERROR_STOP=1 <<-SQL
  DO \$\$
  BEGIN
    IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = '${DB_USER}') THEN
      CREATE ROLE ${DB_USER} WITH LOGIN PASSWORD '${DB_PASSWORD}';
    END IF;
  END
  \$\$;
  SELECT 'CREATE DATABASE ${DB_NAME} OWNER ${DB_USER}'
  WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = '${DB_NAME}')\gexec
SQL

# ── 4. Dedicated system user + app directory ─────────────────────────────

if ! id -u "${APP_USER}" >/dev/null 2>&1; then
  useradd --system --create-home --shell /bin/bash "${APP_USER}"
fi
mkdir -p "${APP_DIR}"
chown "${APP_USER}:${APP_USER}" "${APP_DIR}"

# ── 5. Clone the repo + Python environment ────────────────────────────────

if [ ! -d "${APP_DIR}/.git" ]; then
  sudo -u "${APP_USER}" git clone "${REPO_URL}" "${APP_DIR}"
fi
cd "${APP_DIR}"

sudo -u "${APP_USER}" python3 -m venv "${APP_DIR}/venv"
sudo -u "${APP_USER}" "${APP_DIR}/venv/bin/pip" install --upgrade pip
sudo -u "${APP_USER}" "${APP_DIR}/venv/bin/pip" install -r requirements.txt

# ── 6. .env — generated values + blank placeholders for your own keys ────

DJANGO_SECRET_KEY="$("${APP_DIR}/venv/bin/python" -c "from django.core.management.utils import get_random_secret_key; print(get_random_secret_key())")"
ALLOWED_HOSTS_VALUE="${DOMAIN:-*}"
CSRF_ORIGIN_VALUE="${DOMAIN:+https://${DOMAIN}}"

cat > "${APP_DIR}/.env" <<-ENV
	# Generated by deploy/setup_vps.sh — see .env.example for what every
	# variable does. Anything left blank here degrades to a documented
	# no-op (console email, no push, local disk media) until you set it.

	DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
	DJANGO_DEBUG=false
	DJANGO_ALLOWED_HOSTS=${ALLOWED_HOSTS_VALUE}
	DJANGO_CSRF_TRUSTED_ORIGINS=${CSRF_ORIGIN_VALUE}
	DJANGO_SSL_REDIRECT=${DOMAIN:+true}

	DATABASE_URL=postgres://${DB_USER}:${DB_PASSWORD}@localhost:5432/${DB_NAME}

	# ── Fill these in yourself once the server is up (each has its own
	# section in .env.example with exactly where to get it) ──────────────
	STRIPE_SECRET_KEY=
	STRIPE_PUBLIC_KEY=
	STRIPE_WEBHOOK_SECRET=
	CLOUDINARY_URL=
	RESEND_API_KEY=
	DEFAULT_FROM_EMAIL=noreply@localhost
	FIREBASE_SERVICE_ACCOUNT_B64=
	SIMULATED_BANK_WEBHOOK_SECRET=
	BANK_SIMULATOR_API_KEY=

	# Superuser bootstrap — read once by createsuperuser below, then this
	# script deletes these three lines automatically.
	DJANGO_SUPERUSER_USERNAME=${SUPERUSER_USERNAME}
	DJANGO_SUPERUSER_PASSWORD=${SUPERUSER_PASSWORD}
	DJANGO_SUPERUSER_EMAIL=${SUPERUSER_EMAIL}
ENV
chown "${APP_USER}:${APP_USER}" "${APP_DIR}/.env"
chmod 600 "${APP_DIR}/.env"

# ── 7. Migrate (fresh schema, no data), static files, superuser ──────────

sudo -u "${APP_USER}" bash -c "cd '${APP_DIR}' && venv/bin/python manage.py migrate --noinput"
sudo -u "${APP_USER}" bash -c "cd '${APP_DIR}' && venv/bin/python manage.py update_translation_fields olretail"
sudo -u "${APP_USER}" bash -c "cd '${APP_DIR}' && venv/bin/python manage.py collectstatic --noinput"
# createsuperuser --noinput reads DJANGO_SUPERUSER_USERNAME/_EMAIL/_PASSWORD
# straight from the environment (Django's own built-in support — same
# mechanism the Render deploy already uses in render.yaml).
sudo -u "${APP_USER}" bash -c "cd '${APP_DIR}' && set -a && source .env && set +a && venv/bin/python manage.py createsuperuser --noinput" || true
# Used exactly once, above — strip them out rather than leave a plaintext
# password sitting in the file the running service reads its environment
# from indefinitely.
sed -i '/^DJANGO_SUPERUSER_/d' "${APP_DIR}/.env"

# ── 8. gunicorn as a systemd service ──────────────────────────────────────

cat > /etc/systemd/system/timormart.service <<-SERVICE
	[Unit]
	Description=TimorMart (gunicorn)
	After=network.target postgresql.service

	[Service]
	User=${APP_USER}
	Group=${APP_USER}
	WorkingDirectory=${APP_DIR}
	EnvironmentFile=${APP_DIR}/.env
	ExecStart=${APP_DIR}/venv/bin/gunicorn TLoretail.wsgi --bind 127.0.0.1:8000 --workers 3 --log-file -
	Restart=on-failure

	[Install]
	WantedBy=multi-user.target
SERVICE

systemctl daemon-reload
systemctl enable --now timormart

# ── 9. Nginx reverse proxy + HTTPS (skipped if DOMAIN is blank) ──────────

if [ -n "${DOMAIN}" ]; then
  cat > "/etc/nginx/sites-available/timormart" <<-NGINX
	server {
	    listen 80;
	    server_name ${DOMAIN};

	    location /static/ {
	        alias ${APP_DIR}/staticfiles/;
	    }
	    location /media/ {
	        alias ${APP_DIR}/media/;
	    }
	    location / {
	        proxy_pass http://127.0.0.1:8000;
	        proxy_set_header Host \$host;
	        proxy_set_header X-Real-IP \$remote_addr;
	        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
	        proxy_set_header X-Forwarded-Proto \$scheme;
	    }
	}
NGINX
  ln -sf /etc/nginx/sites-available/timormart /etc/nginx/sites-enabled/timormart
  rm -f /etc/nginx/sites-enabled/default
  nginx -t && systemctl reload nginx
  certbot --nginx -d "${DOMAIN}" --non-interactive --agree-tos -m "${SUPERUSER_EMAIL}" --redirect || \
    echo "Certbot failed — DNS for ${DOMAIN} may not be pointed at this server yet. Re-run: certbot --nginx -d ${DOMAIN}"
else
  echo "DOMAIN was left blank — Nginx/HTTPS setup skipped. The app is reachable on port 8000 on this server only (not exposed)."
fi

# ── 10. Firewall ───────────────────────────────────────────────────────────

ufw allow OpenSSH
ufw allow "Nginx Full"
ufw --force enable

# ── 11. Summary ─────────────────────────────────────────────────────────

echo
echo "=========================================================="
echo "Done. Database is empty except for the superuser account."
echo
echo "Superuser login:"
echo "  username: ${SUPERUSER_USERNAME}"
echo "  email:    ${SUPERUSER_EMAIL}"
echo "  password: (the one you set in this script — change it after first login)"
echo
echo "Postgres role password (saved in ${APP_DIR}/.env, DATABASE_URL):"
echo "  ${DB_PASSWORD}"
echo
echo "Still to do, from .env.example, once you're ready:"
echo "  - STRIPE_SECRET_KEY / STRIPE_PUBLIC_KEY / STRIPE_WEBHOOK_SECRET"
echo "  - CLOUDINARY_URL (product/delivery photos — without this, uploads"
echo "    are saved to local disk, which is fine on a VPS with persistent"
echo "    storage, unlike Render's ephemeral free tier)"
echo "  - RESEND_API_KEY (or GMAIL_*) for real outgoing email"
echo "  - FIREBASE_SERVICE_ACCOUNT_B64 for courier app push notifications"
echo "  - SIMULATED_BANK_WEBHOOK_SECRET / BANK_SIMULATOR_API_KEY only if"
echo "    you're keeping the test bank simulator enabled"
echo
echo "Edit ${APP_DIR}/.env, then: systemctl restart timormart"
echo
echo "Once logged in, everything else (payment instructions, commission"
echo "rate, platform bank accounts, courier delivery fee, etc.) is"
echo "configured from the app's own /dashboard/ — nothing else needs a"
echo "server-side change."
echo "=========================================================="
