# Generated by Django 3.1.4 on 2021-07-29 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olretail', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='aprroved',
            field=models.BooleanField(null=True),
        ),
    ]
