# Generated by Django 3.1.4 on 2021-08-03 00:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('olretail', '0002_auto_20210729_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='country',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='olretail.country'),
        ),
        migrations.AlterField(
            model_name='product',
            name='aprroved',
            field=models.BooleanField(default=False),
        ),
    ]
