# Generated by Django 3.1.4 on 2021-08-03 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('olretail', '0004_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
