# Generated by Django 5.2.16 on 2026-07-14 05:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olretail', '0005_comment_sentiment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=20, unique=True)),
                ('quantity', models.PositiveIntegerField()),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=13)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=13)),
                ('commission_amount', models.DecimalField(decimal_places=2, default=0, max_digits=13)),
                ('payment_fee', models.DecimalField(decimal_places=2, default=0, max_digits=13)),
                ('total', models.DecimalField(decimal_places=2, max_digits=13)),
                ('status', models.CharField(choices=[('pending_payment', 'Pending Payment'), ('paid', 'Payment Received'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], db_index=True, default='pending_payment', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('delivery_address', models.TextField()),
                ('delivery_phone', models.CharField(max_length=40)),
                ('estimated_delivery', models.DateField(blank=True, null=True)),
                ('buyer_notes', models.TextField(blank=True)),
                ('admin_notes', models.TextField(blank=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='olretail.product')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='olretail.seller')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Dispute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dispute_id', models.CharField(max_length=20, unique=True)),
                ('reason', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('buyer_evidence', models.TextField(blank=True)),
                ('seller_response', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('open', 'Open - Awaiting Seller Response'), ('seller_response', 'Seller Responded'), ('under_review', 'Under Admin Review'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='open', max_length=30)),
                ('resolution', models.CharField(blank=True, choices=[('refund_full', 'Full Refund to Buyer'), ('refund_partial', 'Partial Refund'), ('reshipment', 'Reshipment'), ('no_action', 'Closed - No Action')], max_length=30)),
                ('refund_amount', models.DecimalField(decimal_places=2, default=0, max_digits=13)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('seller_response_deadline', models.DateTimeField()),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='disputes_initiated', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disputes_resolved', to=settings.AUTH_USER_MODEL)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='disputes_received', to='olretail.seller')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='dispute', to='olretail.order')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_payment_intent_id', models.CharField(max_length=255, unique=True)),
                ('stripe_charge_id', models.CharField(blank=True, max_length=255)),
                ('amount_cents', models.BigIntegerField()),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], db_index=True, default='pending', max_length=20)),
                ('payment_method_type', models.CharField(max_length=50)),
                ('payment_method_last4', models.CharField(blank=True, max_length=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('succeeded_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('webhook_received', models.BooleanField(default=False)),
                ('webhook_received_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='payment', to='olretail.order')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payout_id', models.CharField(max_length=20, unique=True)),
                ('amount_cents', models.BigIntegerField()),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('processing', 'Processing'), ('paid', 'Paid'), ('failed', 'Failed')], default='scheduled', max_length=20)),
                ('bank_name', models.CharField(blank=True, max_length=255)),
                ('account_number', models.CharField(blank=True, max_length=50)),
                ('account_holder', models.CharField(blank=True, max_length=255)),
                ('stripe_payout_id', models.CharField(blank=True, max_length=255)),
                ('scheduled_date', models.DateField()),
                ('paid_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payouts', to='olretail.seller')),
            ],
            options={
                'ordering': ['-scheduled_date'],
            },
        ),
        migrations.CreateModel(
            name='SellerBalance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_earnings', models.BigIntegerField(default=0)),
                ('total_payouts', models.BigIntegerField(default=0)),
                ('pending_payout', models.BigIntegerField(default=0)),
                ('available_balance', models.BigIntegerField(default=0)),
                ('min_payout_cents', models.BigIntegerField(default=50000)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seller', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='balance', to='olretail.seller')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_cents', models.BigIntegerField()),
                ('transaction_type', models.CharField(choices=[('commission', 'Commission'), ('refund', 'Refund'), ('adjustment', 'Adjustment'), ('payout', 'Payout')], max_length=20)),
                ('description', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='olretail.order')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='olretail.seller')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carts', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='olretail.product')),
            ],
            options={
                'ordering': ['-added_at'],
                'unique_together': {('buyer', 'product')},
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['buyer', '-created_at'], name='olretail_or_buyer_i_7ecf33_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['seller', '-created_at'], name='olretail_or_seller__a4539f_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', '-created_at'], name='olretail_or_status_1a1101_idx'),
        ),
        migrations.AddIndex(
            model_name='dispute',
            index=models.Index(fields=['status', '-created_at'], name='olretail_di_status_01f6c9_idx'),
        ),
        migrations.AddIndex(
            model_name='dispute',
            index=models.Index(fields=['seller', 'status'], name='olretail_di_seller__8f8d74_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['order', 'status'], name='olretail_pa_order_i_18c190_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status', '-created_at'], name='olretail_pa_status_0fd777_idx'),
        ),
        migrations.AddIndex(
            model_name='payout',
            index=models.Index(fields=['seller', 'status'], name='olretail_pa_seller__5a4b4f_idx'),
        ),
        migrations.AddIndex(
            model_name='payout',
            index=models.Index(fields=['status', '-scheduled_date'], name='olretail_pa_status_690e49_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['seller', '-created_at'], name='olretail_tr_seller__f92d4d_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['transaction_type', '-created_at'], name='olretail_tr_transac_21beaf_idx'),
        ),
    ]
