# Generated by Django 5.2.16 on 2026-07-14 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olretail', '0006_order_dispute_payment_payout_sellerbalance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispute',
            name='reason',
            field=models.CharField(choices=[('not_received', 'Item Not Received'), ('damaged', 'Item Damaged'), ('not_as_described', 'Item Not as Described'), ('wrong_item', 'Wrong Item Received'), ('other', 'Other')], max_length=100),
        ),
    ]
