# Generated by Django 5.2.16 on 2026-07-14 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olretail', '0007_alter_dispute_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('stripe', 'Card (Stripe)'), ('bank_transfer', 'Bank / Mobile Transfer')], default='stripe', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_reported_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='seller',
            name='payment_instructions',
            field=models.TextField(blank=True, help_text='Bank or mobile money details buyers use to pay you directly (e.g. bank name, account number, account holder name).'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending_payment', 'Pending Payment'), ('payment_reported', 'Payment Reported — Awaiting Confirmation'), ('paid', 'Payment Received'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], db_index=True, default='pending_payment', max_length=20),
        ),
    ]
