# Generated by Django 3.1.4 on 2021-09-20 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olretail', '0009_auto_20210805_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_image_2',
            field=models.ImageField(blank=True, default=True, upload_to='product_image'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_image_3',
            field=models.ImageField(blank=True, default=True, upload_to='product_image'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=13),
        ),
    ]
