# Generated by Django 5.2.16 on 2026-07-14 13:19
# Hand-edited: reordered so Payment.order -> Order.payment data is copied
# before the old field is dropped (Payment used to be one-to-one with a
# single Order, which silently dropped every order but the first when a
# cart spanned several sellers in one Stripe checkout — see Order.payment).

import django.db.models.deletion
from django.db import migrations, models


def copy_payment_order_to_order_payment(apps, schema_editor):
    Payment = apps.get_model('olretail', 'Payment')
    for payment in Payment.objects.all():
        order = payment.order
        order.payment_id = payment.id
        order.save(update_fields=['payment'])


class Migration(migrations.Migration):

    dependencies = [
        ('olretail', '0010_order_delivery_photo_courier_order_assigned_courier'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='olretail.payment'),
        ),
        migrations.RunPython(copy_payment_order_to_order_payment, migrations.RunPython.noop),
        migrations.RemoveIndex(
            model_name='payment',
            name='olretail_pa_order_i_18c190_idx',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='order',
        ),
    ]
