# Generated by Django 3.1.4 on 2021-09-21 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olretail', '0011_auto_20210920_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='title_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='title_pt',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='title_tt',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
