# Generated by Django 5.2.16 on 2026-07-14 13:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olretail', '0011_remove_payment_olretail_pa_order_i_18c190_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SellerSubscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(choices=[('free', 'Free'), ('monthly', 'Monthly — $11/month'), ('yearly', 'Yearly — $100/year')], default='free', max_length=10)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seller', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='olretail.seller')),
            ],
        ),
        migrations.CreateModel(
            name='SubscriptionRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(choices=[('monthly', 'Monthly — $11/month'), ('yearly', 'Yearly — $100/year')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('payment_reference', models.TextField(help_text='How/when you paid — e.g. bank transfer reference, mobile money confirmation.')),
                ('status', models.CharField(choices=[('pending', 'Payment Reported — Awaiting Confirmation'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('admin_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_requests', to='olretail.seller')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
