# Generated by Django 5.2.16 on 2026-07-15 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olretail', '0012_sellersubscription_subscriptionrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_instructions', models.TextField(blank=True, help_text='Bank or mobile money details shown to sellers when they pay the platform for a subscription upgrade.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Platform settings',
            },
        ),
    ]
