# Generated by Django 3.1.4 on 2021-09-22 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('olretail', '0012_auto_20210921_1459'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='title_pt',
        ),
    ]
