# Generated by Django 5.2.16 on 2026-07-16 01:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olretail', '0015_alter_notification_message_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='courier',
            name='service_cities',
            field=models.ManyToManyField(blank=True, help_text='Cities this courier delivers to. Leave empty if not yet configured (order dropdowns will show all couriers until this is set).', related_name='couriers', to='olretail.city'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deliveries', to='olretail.city'),
        ),
    ]
