# Generated by Django 5.2.16 on 2026-07-16 02:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.utils import timezone


def grandfather_existing_couriers(apps, schema_editor):
    """Couriers created before this feature shipped have no track record to
    lose — mark them verified so they don't vanish from assignment dropdowns.
    Only couriers added after this migration go through real review."""
    Courier = apps.get_model('olretail', 'Courier')
    Courier.objects.update(
        verification_status='verified',
        verified_at=timezone.now(),
        verification_note='Grandfathered — existing courier before verification system was introduced.',
    )


class Migration(migrations.Migration):

    dependencies = [
        ('olretail', '0016_courier_service_cities_order_delivery_city'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='courier',
            name='deposit_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='courier',
            name='id_document',
            field=models.ImageField(blank=True, null=True, upload_to='courier_ids/'),
        ),
        migrations.AddField(
            model_name='courier',
            name='verification_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='courier',
            name='verification_status',
            field=models.CharField(choices=[('pending', 'Pending Verification'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='courier',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='courier',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='couriers_verified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='CourierRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courier_ratings_given', to=settings.AUTH_USER_MODEL)),
                ('courier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='olretail.courier')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='courier_rating', to='olretail.order')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RunPython(grandfather_existing_couriers, migrations.RunPython.noop),
    ]
