# Generated by Django 5.2.16 on 2026-07-16 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olretail', '0017_courier_deposit_amount_courier_id_document_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='company_address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='seller',
            name='company_bank_account',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='seller',
            name='company_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='seller',
            name='company_tin',
            field=models.CharField(blank=True, max_length=50, verbose_name='TIN'),
        ),
        migrations.AddField(
            model_name='seller',
            name='seller_type',
            field=models.CharField(choices=[('individual', 'Individual'), ('company', 'Company')], default='individual', max_length=20),
        ),
    ]
