# Generated by Django 5.2.16 on 2026-07-16 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olretail', '0018_seller_company_address_seller_company_bank_account_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pieces_per_unit',
            field=models.PositiveIntegerField(blank=True, help_text='e.g. 12 pens in a pack', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.CharField(blank=True, help_text='e.g. L, 42, 500ml', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='units_per_box',
            field=models.PositiveIntegerField(blank=True, help_text='e.g. 24 packs in a box', null=True),
        ),
    ]
