# Generated by Django 5.2.16 on 2026-07-16 13:48

import django.db.models.deletion
from django.db import migrations, models


def create_restaurant_category(apps, schema_editor):
    """A dedicated Category row for restaurant menu items — deliberately
    separate from the pre-existing "food" category (id 5), which already
    has real grocery-type products under it. Reusing that one would show
    restaurant-only fields (prep time, availability) on unrelated listings.

    Category.title is a django-modeltranslation field: the live model reads
    from title_en/title_tet shadow columns, but those aren't part of this
    migration's frozen historical model (modeltranslation injects them at
    app-load time, not via Django's migration state) — so they're set here
    with raw SQL alongside the plain fallback `title` column."""
    Category = apps.get_model('olretail', 'Category')
    category, created = Category.objects.get_or_create(slug='restaurant', defaults={'title': 'Restaurant'})
    if created:
        with schema_editor.connection.cursor() as cursor:
            cursor.execute(
                "UPDATE olretail_category SET title_en = %s WHERE id = %s",
                ['Restaurant', category.pk],
            )


class Migration(migrations.Migration):

    dependencies = [
        ('olretail', '0020_seller_business_document_seller_verification_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='delivery_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='order',
            name='food_status',
            field=models.CharField(blank=True, choices=[('received', 'Order Received'), ('preparing', 'Preparing Food'), ('ready_for_pickup', 'Ready for Pickup'), ('picked_up', 'Picked Up'), ('on_the_way', 'On the Way')], max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='prep_time_minutes',
            field=models.PositiveIntegerField(blank=True, help_text='e.g. 20', null=True),
        ),
        migrations.AlterField(
            model_name='seller',
            name='seller_type',
            field=models.CharField(choices=[('individual', 'Individual'), ('company', 'Company'), ('restaurant', 'Restaurant')], default='individual', max_length=20),
        ),
        migrations.CreateModel(
            name='MenuCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_categories', to='olretail.seller')),
            ],
            options={
                'verbose_name_plural': 'Menu categories',
                'ordering': ['display_order', 'name'],
                'unique_together': {('seller', 'name')},
            },
        ),
        migrations.AddField(
            model_name='product',
            name='menu_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='olretail.menucategory'),
        ),
        migrations.RunPython(create_restaurant_category, migrations.RunPython.noop),
    ]
