# Generated by Django 5.2.16 on 2026-07-16 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olretail', '0021_city_delivery_fee_order_food_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=13),
        ),
    ]
