# Generated by Django 5.2.16 on 2026-07-17 05:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olretail', '0022_order_delivery_fee'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdempotencyRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255, unique=True)),
                ('endpoint', models.CharField(max_length=100)),
                ('request_fingerprint', models.CharField(max_length=64)),
                ('response_status', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('response_body', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='VirtualBankAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=34, unique=True)),
                ('account_holder_name', models.CharField(max_length=255)),
                ('bank_name', models.CharField(default='TimorMart Simulated Bank', max_length=255)),
                ('balance_cents', models.BigIntegerField(default=0)),
                ('status', models.CharField(choices=[('active', 'Active'), ('closed', 'Closed'), ('frozen', 'Frozen')], default='active', max_length=10)),
                ('forced_outcome', models.CharField(choices=[('auto', 'Automatic (balance-based)'), ('always_success', 'Always Succeed'), ('always_fail', 'Always Fail'), ('always_timeout', 'Always Timeout'), ('always_insufficient_funds', 'Always Insufficient Funds'), ('always_duplicate', 'Always Flag as Duplicate')], default='auto', max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['account_number'],
            },
        ),
        migrations.AddField(
            model_name='payment',
            name='gateway',
            field=models.CharField(choices=[('stripe', 'Card (Stripe)'), ('bank_transfer', 'Bank / Mobile Transfer'), ('simulated_bank', 'Automated Bank Transfer (Test)')], default='stripe', max_length=20),
        ),
        migrations.AddField(
            model_name='payment',
            name='gateway_reference',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('stripe', 'Card (Stripe)'), ('bank_transfer', 'Bank / Mobile Transfer'), ('simulated_bank', 'Automated Bank Transfer (Test)')], default='stripe', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='stripe_payment_intent_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='SimulatedBankTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=40, unique=True)),
                ('account_number_submitted', models.CharField(max_length=34)),
                ('amount_cents', models.BigIntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('timeout', 'Timeout'), ('insufficient_funds', 'Insufficient Funds'), ('invalid_account', 'Invalid / Closed Account'), ('duplicate', 'Duplicate Transaction')], default='pending', max_length=20)),
                ('pending_outcome', models.CharField(blank=True, choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('timeout', 'Timeout'), ('insufficient_funds', 'Insufficient Funds'), ('invalid_account', 'Invalid / Closed Account'), ('duplicate', 'Duplicate Transaction')], max_length=20)),
                ('attempt_count', models.PositiveIntegerField(default=1)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('settle_after', models.DateTimeField(blank=True, null=True)),
                ('settled_at', models.DateTimeField(blank=True, null=True)),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bank_simulation', to='olretail.payment')),
                ('source_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='olretail.virtualbankaccount')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GatewayEventLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('outbound', 'Outbound'), ('inbound', 'Inbound')], max_length=10)),
                ('event_type', models.CharField(max_length=50)),
                ('request_payload', models.JSONField(blank=True, default=dict)),
                ('response_payload', models.JSONField(blank=True, default=dict)),
                ('status_code', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_logs', to='olretail.simulatedbanktransaction')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='simulatedbanktransaction',
            index=models.Index(fields=['status', '-created_at'], name='olretail_si_status_1fd87f_idx'),
        ),
    ]
