# Generated by Django 5.2.16 on 2026-07-18 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olretail', '0024_reviews_wishlist_abandoned_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='title_ind',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='title_pt_pt',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
