# Generated by Django 5.2.16 on 2026-07-21 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olretail', '0025_category_title_ind_category_title_pt_pt'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_ind',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_pt_pt',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_tet',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='features',
            field=models.TextField(blank=True, help_text='One per line, e.g. "Hand-woven".'),
        ),
        migrations.AddField(
            model_name='product',
            name='features_en',
            field=models.TextField(blank=True, help_text='One per line, e.g. "Hand-woven".', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='features_ind',
            field=models.TextField(blank=True, help_text='One per line, e.g. "Hand-woven".', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='features_pt_pt',
            field=models.TextField(blank=True, help_text='One per line, e.g. "Hand-woven".', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='features_tet',
            field=models.TextField(blank=True, help_text='One per line, e.g. "Hand-woven".', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='name_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='name_ind',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='name_pt_pt',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='name_tet',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='seo_description',
            field=models.CharField(blank=True, help_text='Optional — shown in search engine results instead of the description.', max_length=160),
        ),
        migrations.AddField(
            model_name='product',
            name='seo_description_en',
            field=models.CharField(blank=True, help_text='Optional — shown in search engine results instead of the description.', max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='seo_description_ind',
            field=models.CharField(blank=True, help_text='Optional — shown in search engine results instead of the description.', max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='seo_description_pt_pt',
            field=models.CharField(blank=True, help_text='Optional — shown in search engine results instead of the description.', max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='seo_description_tet',
            field=models.CharField(blank=True, help_text='Optional — shown in search engine results instead of the description.', max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='seo_title',
            field=models.CharField(blank=True, help_text='Optional — shown in search engine results instead of the product name.', max_length=70),
        ),
        migrations.AddField(
            model_name='product',
            name='seo_title_en',
            field=models.CharField(blank=True, help_text='Optional — shown in search engine results instead of the product name.', max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='seo_title_ind',
            field=models.CharField(blank=True, help_text='Optional — shown in search engine results instead of the product name.', max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='seo_title_pt_pt',
            field=models.CharField(blank=True, help_text='Optional — shown in search engine results instead of the product name.', max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='seo_title_tet',
            field=models.CharField(blank=True, help_text='Optional — shown in search engine results instead of the product name.', max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='short_description',
            field=models.CharField(blank=True, help_text='A one-line summary shown in listings.', max_length=300),
        ),
        migrations.AddField(
            model_name='product',
            name='short_description_en',
            field=models.CharField(blank=True, help_text='A one-line summary shown in listings.', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='short_description_ind',
            field=models.CharField(blank=True, help_text='A one-line summary shown in listings.', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='short_description_pt_pt',
            field=models.CharField(blank=True, help_text='A one-line summary shown in listings.', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='short_description_tet',
            field=models.CharField(blank=True, help_text='A one-line summary shown in listings.', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='specifications',
            field=models.TextField(blank=True, help_text='One per line, e.g. "Weight: 500g".'),
        ),
        migrations.AddField(
            model_name='product',
            name='specifications_en',
            field=models.TextField(blank=True, help_text='One per line, e.g. "Weight: 500g".', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='specifications_ind',
            field=models.TextField(blank=True, help_text='One per line, e.g. "Weight: 500g".', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='specifications_pt_pt',
            field=models.TextField(blank=True, help_text='One per line, e.g. "Weight: 500g".', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='specifications_tet',
            field=models.TextField(blank=True, help_text='One per line, e.g. "Weight: 500g".', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.CharField(blank=True, help_text='Optional — comma-separated, e.g. "scarf, wool, winter".', max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='tags_en',
            field=models.CharField(blank=True, help_text='Optional — comma-separated, e.g. "scarf, wool, winter".', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='tags_ind',
            field=models.CharField(blank=True, help_text='Optional — comma-separated, e.g. "scarf, wool, winter".', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='tags_pt_pt',
            field=models.CharField(blank=True, help_text='Optional — comma-separated, e.g. "scarf, wool, winter".', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='tags_tet',
            field=models.CharField(blank=True, help_text='Optional — comma-separated, e.g. "scarf, wool, winter".', max_length=255, null=True),
        ),
    ]
