# Generated by Django 5.2.16 on 2026-07-21 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olretail', '0026_product_description_en_product_description_ind_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='director_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='seller',
            name='director_id_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='Director ID / TIN Number'),
        ),
        migrations.AddField(
            model_name='seller',
            name='director_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='seller',
            name='director_phone',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
