# Generated by Django 5.2.16 on 2026-07-21 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olretail', '0027_seller_director_email_seller_director_id_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('commission', 'Order earnings'), ('refund', 'Refund'), ('adjustment', 'Adjustment'), ('payout', 'Payout')], max_length=20),
        ),
    ]
