# Generated by Django 5.2.16 on 2026-07-23 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olretail', '0029_devicetoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_amount_claimed',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_flag_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_flagged',
            field=models.BooleanField(default=False, help_text='Auto-flagged (amount mismatch or reused receipt) for priority admin review.'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_proof',
            field=models.ImageField(blank=True, null=True, upload_to='payment_proofs/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_proof_hash',
            field=models.CharField(blank=True, db_index=True, help_text='SHA-256 of the uploaded proof image — catches the same receipt being reused across orders.', max_length=64),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_reference',
            field=models.CharField(blank=True, help_text='Bank/mobile transfer reference or transaction number.', max_length=100),
        ),
        migrations.AlterField(
            model_name='dispute',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='disputes', to='olretail.order'),
        ),
        migrations.AlterField(
            model_name='dispute',
            name='reason',
            field=models.CharField(choices=[('not_received', 'Item Not Received'), ('damaged', 'Item Damaged'), ('not_as_described', 'Item Not as Described'), ('wrong_item', 'Wrong Item Received'), ('other', 'Other'), ('payment_not_received', 'Seller Reports Payment Not Received'), ('payment_no_response', 'Seller Did Not Respond to Payment Claim')], max_length=100),
        ),
        migrations.AlterField(
            model_name='dispute',
            name='resolution',
            field=models.CharField(blank=True, choices=[('refund_full', 'Full Refund to Buyer'), ('refund_partial', 'Partial Refund'), ('reshipment', 'Reshipment'), ('no_action', 'Closed - No Action'), ('payment_confirmed', 'Payment Confirmed — Order Marked Paid'), ('payment_rejected', 'Payment Claim Rejected — Order Cancelled')], max_length=30),
        ),
    ]
