# Generated by Django 5.2.16 on 2026-07-24 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olretail', '0030_order_payment_amount_claimed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('stripe', 'Card (Stripe)'), ('bank_transfer', 'Bank / Mobile Transfer'), ('cash_on_delivery', 'Cash on Delivery'), ('simulated_bank', 'Automated Bank Transfer (Test)')], default='stripe', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='gateway',
            field=models.CharField(choices=[('stripe', 'Card (Stripe)'), ('bank_transfer', 'Bank / Mobile Transfer'), ('cash_on_delivery', 'Cash on Delivery'), ('simulated_bank', 'Automated Bank Transfer (Test)')], default='stripe', max_length=20),
        ),
    ]
