# Generated by Django 5.2.16 on 2026-07-24 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olretail', '0031_alter_order_payment_method_alter_payment_gateway'),
    ]

    operations = [
        migrations.AddField(
            model_name='courier',
            name='driving_license',
            field=models.ImageField(blank=True, null=True, upload_to='courier_licenses/'),
        ),
        migrations.AddField(
            model_name='courier',
            name='whatsapp',
            field=models.CharField(blank=True, help_text='WhatsApp number for delivery coordination.', max_length=40),
        ),
    ]
