# Generated by Django 5.2.16 on 2026-07-24 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('olretail', '0032_courier_driving_license_courier_whatsapp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courier',
            name='whatsapp',
        ),
    ]
