# Generated by Django 5.2.16 on 2026-07-26 02:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olretail', '0034_create_vehicle_rental_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name_plural': 'Business Categories',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Municipality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Municipalities',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='seller',
            name='administrative_post',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='seller',
            name='aldeia',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='seller',
            name='business_registration_number',
            field=models.CharField(blank=True, help_text='Official business/company registration number, distinct from the TIN.', max_length=100),
        ),
        migrations.AddField(
            model_name='seller',
            name='cash_on_delivery_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='seller',
            name='closing_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='seller',
            name='contact_person_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='seller',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='seller_cover_images/'),
        ),
        migrations.AddField(
            model_name='seller',
            name='delivery_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='seller',
            name='full_address',
            field=models.CharField(blank=True, help_text='Detailed street-level business address.', max_length=255),
        ),
        migrations.AddField(
            model_name='seller',
            name='gps_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='seller',
            name='gps_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='seller',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='seller_logos/'),
        ),
        migrations.AddField(
            model_name='seller',
            name='opening_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='seller',
            name='pickup_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='seller',
            name='suco',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='seller',
            name='whatsapp_number_override',
            field=models.CharField(blank=True, help_text='Leave blank to use your phone number for WhatsApp.', max_length=40),
        ),
        migrations.AlterField(
            model_name='seller',
            name='seller_type',
            field=models.CharField(choices=[('individual', 'Individual'), ('registered_business', 'Registered Business'), ('cooperative', 'Cooperative'), ('government', 'Government Institution'), ('ngo', 'NGO / Non-Profit')], default='individual', max_length=20),
        ),
        migrations.AddField(
            model_name='seller',
            name='business_categories',
            field=models.ManyToManyField(blank=True, related_name='sellers', to='olretail.businesscategory'),
        ),
        migrations.AddField(
            model_name='seller',
            name='municipality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sellers', to='olretail.municipality'),
        ),
    ]
