# Generated by Django 5.2.16 on 2026-07-27 02:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olretail', '0037_migrate_legacy_seller_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='olretail.country'),
        ),
        migrations.AlterField(
            model_name='product',
            name='item_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='olretail.city'),
        ),
    ]
