# Generated by Django 5.2.16 on 2026-07-27 06:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olretail', '0039_sellerbankaccount'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformBankAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_holder_name', models.CharField(max_length=200)),
                ('bank_name', models.CharField(max_length=200)),
                ('account_number', models.CharField(max_length=50)),
                ('swift_code', models.CharField(blank=True, max_length=11, verbose_name='SWIFT/BIC code')),
                ('iban', models.CharField(blank=True, max_length=34, verbose_name='IBAN')),
                ('settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to='olretail.platformsettings')),
            ],
            options={
                'verbose_name_plural': 'Platform bank accounts',
                'ordering': ['id'],
            },
        ),
    ]
