# Generated by Django 5.2.16 on 2026-07-27 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olretail', '0040_platformbankaccount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispute',
            name='reason',
            field=models.CharField(choices=[('not_received', 'Item Not Received'), ('damaged', 'Item Damaged'), ('not_as_described', 'Item Not as Described'), ('wrong_item', 'Wrong Item Received'), ('other', 'Other'), ('payment_claim_submitted', 'Bank Transfer Payment Claim'), ('payment_not_received', 'Seller Reports Payment Not Received'), ('payment_no_response', 'Seller Did Not Respond to Payment Claim')], max_length=100),
        ),
    ]
