# Generated by Django 5.2.16 on 2026-07-31 02:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olretail', '0041_alter_dispute_reason'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourierAvailability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.PositiveSmallIntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('courier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_windows', to='olretail.courier')),
            ],
            options={
                'verbose_name_plural': 'Courier availability windows',
                'ordering': ['weekday', 'start_time'],
            },
        ),
    ]
