# Generated by Django 5.2.16 on 2026-08-02 01:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olretail', '0042_courieravailability'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='courier_fee_cents',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='courier_delivery_fee_cents',
            field=models.BigIntegerField(default=200, help_text='Flat fee (in cents) a courier earns for each delivery they confirm. $2.00 = 200.'),
        ),
        migrations.CreateModel(
            name='CourierBalance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_earnings', models.BigIntegerField(default=0)),
                ('total_payouts', models.BigIntegerField(default=0)),
                ('pending_payout', models.BigIntegerField(default=0)),
                ('available_balance', models.BigIntegerField(default=0)),
                ('min_payout_cents', models.BigIntegerField(default=2000)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('courier', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='balance', to='olretail.courier')),
            ],
        ),
        migrations.CreateModel(
            name='CourierPayout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payout_id', models.CharField(max_length=20, unique=True)),
                ('amount_cents', models.BigIntegerField()),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('processing', 'Processing'), ('paid', 'Paid'), ('failed', 'Failed')], default='scheduled', max_length=20)),
                ('bank_name', models.CharField(blank=True, max_length=255)),
                ('account_number', models.CharField(blank=True, max_length=50)),
                ('account_holder', models.CharField(blank=True, max_length=255)),
                ('scheduled_date', models.DateField()),
                ('paid_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('courier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payouts', to='olretail.courier')),
            ],
            options={
                'ordering': ['-scheduled_date'],
                'indexes': [models.Index(fields=['courier', 'status'], name='olretail_co_courier_4dbc2d_idx'), models.Index(fields=['status', '-scheduled_date'], name='olretail_co_status_94687e_idx')],
            },
        ),
    ]
