# Generated by Django 5.2.16 on 2026-08-02 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olretail', '0043_order_courier_fee_cents_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platformsettings',
            name='courier_delivery_fee_cents',
            field=models.BigIntegerField(default=100, help_text='Flat fee (in cents) a courier earns for each delivery they confirm. $1.00 = 100.'),
        ),
    ]
