# Generated by Django 5.2.16 on 2026-08-04 09:57

from django.db import migrations, models


def backfill_courier_assignment_status(apps, schema_editor):
    """Every Shipped/Delivered order with an assigned_courier predates this
    feature — treat it as already accepted-and-picked-up so the new
    mark-delivered gate (courier_assignment_status == PICKED_UP) doesn't
    lock an in-flight courier out of a delivery they're already handling.
    Self-delivery orders and restaurant orders are untouched (they never
    get this field set at all — see CourierAssignmentStatus docstring)."""
    Order = apps.get_model('olretail', 'Order')
    Order.objects.filter(
        status__in=['shipped', 'delivered'],
        assigned_courier__isnull=False,
        courier_assignment_status='',
    ).update(
        courier_assignment_status='picked_up',
        courier_assigned_at=models.F('shipped_at'),
    )


class Migration(migrations.Migration):

    dependencies = [
        ('olretail', '0045_order_delivery_latitude_order_delivery_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='courier_assigned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='courier_assignment_status',
            field=models.CharField(blank=True, choices=[('awaiting_response', 'Awaiting Courier Response'), ('accepted', 'Accepted — Awaiting Pickup'), ('picked_up', 'Picked Up'), ('rejected', 'Rejected')], max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='courier_responded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(backfill_courier_assignment_status, migrations.RunPython.noop),
    ]
