# Generated by Django 5.2.16 on 2026-08-05 02:49

from django.db import migrations, models


def backfill_courier_assignment_status(apps, schema_editor):
    """Re-runs the exact same backfill as migration 0046, now that the
    accept/reject/pickup-confirm handshake applies uniformly to every
    order type including restaurant. A handful of orders (food and
    otherwise) got shipped+assigned in the window between 0046 running and
    this change landing, so they still have a blank
    courier_assignment_status despite already being Shipped/Delivered —
    without this, an in-flight courier on one of them would suddenly be
    unable to mark it delivered once the is_restaurant_category carve-out
    in _courier_can_mark_delivered is removed. Same reasoning as 0046:
    treat every pre-existing assignment as already accepted-and-picked-up."""
    Order = apps.get_model('olretail', 'Order')
    Order.objects.filter(
        status__in=['shipped', 'delivered'],
        assigned_courier__isnull=False,
        courier_assignment_status='',
    ).update(
        courier_assignment_status='picked_up',
        courier_assigned_at=models.F('shipped_at'),
    )


class Migration(migrations.Migration):

    dependencies = [
        ('olretail', '0046_order_courier_assigned_at_and_more'),
    ]

    operations = [
        migrations.RunPython(backfill_courier_assignment_status, migrations.RunPython.noop),
    ]
